
共有2个客户端,每个客户端的epoch都为4
*******training************
第1 client的 1(共有4轮)
/Users/taro/Downloads/fedKDD/train.py:123: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img, volatile=True)
/Users/taro/Downloads/fedKDD/train.py:124: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  label = Variable(label, volatile=True)
Finish 1 epoch, Loss: 1.131245, Acc: 0.749984
*******test************
第1个客户端单独训练的测试结果
Test Loss: 1.227774, Acc: 0.792647
*******training************
第1 client的 2(共有4轮)
Finish 2 epoch, Loss: 1.224378, Acc: 0.792561
*******test************
第1个客户端单独训练的测试结果
Test Loss: 1.031968, Acc: 0.792769
*******training************
第1 client的 3(共有4轮)
Finish 3 epoch, Loss: 0.921877, Acc: 0.792769
*******training************
第1 client的 4(共有4轮)
Finish 4 epoch, Loss: 0.737923, Acc: 0.792555
----------------第1个客户端训练结束---------------
*******training************
第2 client的 1(共有4轮)
Finish 1 epoch, Loss: 1.060958, Acc: 0.784982
*******test************
第2个客户端单独训练的测试结果
Test Loss: 1.263272, Acc: 0.794375
*******training************
第2 client的 2(共有4轮)
Finish 2 epoch, Loss: 1.175734, Acc: 0.792207
*******training************
第2 client的 3(共有4轮)
Finish 3 epoch, Loss: 0.984836, Acc: 0.792108
*******training************
第2 client的 4(共有4轮)
Finish 4 epoch, Loss: 0.791349, Acc: 0.792085
/Users/taro/Downloads/fedKDD/train.py:217: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img, volatile=True)
/Users/taro/Downloads/fedKDD/train.py:218: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  label = Variable(label, volatile=True)
----------------第2个客户端训练结束---------------
----------------模型聚合后测试结果----------------------
第1个客户端测试结果
Test Loss: 1.051936, Acc: 0.792175
第2个客户端测试结果
Test Loss: 1.050199, Acc: 0.793997
Traceback (most recent call last):
  File "/Users/taro/Downloads/fedKDD/train.py", line 260, in <module>
    single_test(model_new,test_data[2],test_data_len[2],2)
IndexError: list index out of range